dependencies:
  flutter:
    sdk: flutter
  
  # Thêm các gói sau đây
  flutter_quill: ^7.4.6
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  
  # Các gói hiện có khác
  provider: ^x.x.x
  # ... 