workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.note
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Configure code signing settings"
      - name: Configure iOS project
    script: |
      pod update
      rm -rf build/ios
      mkdir -p build/ios/Release-iphoneos/shared_preferences_foundation/shared_preferences_foundation_privacy.bundle
      touch build/ios/Release-iphoneos/shared_preferences_foundation/shared_preferences_foundation_privacy.bundle/shared_preferences_foundation_privacy

      - name: Flutter packages get
        script: |
          flutter packages pub get
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - "/tmp/xcodebuild_logs/*.log"
      - flutter_drive.log
