workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_pro
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.note
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        VALIDATE_WORKSPACE: "NO"
        VALIDATE_PRODUCT: "NO"
        DISABLE_BUNDLE_VALIDATION: "YES"
      flutter: stable
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Configure code signing settings"
      
      - name: Create ALL possible privacy bundles
        script: |
          cd $CM_BUILD_DIR
          
          # Tạo thư mục Release-iphoneos
          mkdir -p build/ios/Release-iphoneos
          
          # Liệt kê tất cả các thư viện phổ biến có thể cần privacy bundles
          PODS_TO_CHECK=(
            "permission_handler_apple"
            "shared_preferences_foundation"
            "in_app_purchase_storekit"
            "path_provider_foundation"
            "nanopb"
            "leveldb-library"
            "image_picker_ios"
            "google_sign_in_ios"
            "flutter_local_notifications"
            "connectivity_plus"
            "abseil"
            "GoogleUtilities"
            "GTMSessionFetcher"
            "BoringSSL-GRPC"
            "AppAuth"
            "FirebaseCoreInternal"
            "FirebaseCore"
            "FirebaseAuth"
            "FirebaseStorage"
            "FirebaseFirestore"
            "firebase_core"
            "firebase_auth"
            "firebase_storage"
            "cloud_firestore"
            "gRPC-Core"
            "gRPC-C++"
          )
          
          # Tạo tất cả các loại privacy bundle có thể cho từng pod
          for pod in "${PODS_TO_CHECK[@]}"
          do
            # Đảm bảo thư mục tồn tại
            mkdir -p "build/ios/Release-iphoneos/${pod}"

            # Tạo các biến thể privacy bundle có thể có
            BUNDLE_NAMES=(
              "${pod}_privacy"
              "${pod}_Privacy"
              "$(echo ${pod} | sed 's/-/_/g')_privacy"
              "$(echo ${pod} | sed 's/-/_/g')_Privacy"
              "${pod}_Core_Privacy"
              "${pod}_Full_Privacy"
              "openssl_grpc"
              "xcprivacy"
            )
            
            # Tạo tất cả các khả năng
            for bundle_name in "${BUNDLE_NAMES[@]}"
            do
              mkdir -p "build/ios/Release-iphoneos/${pod}/${bundle_name}.bundle"
              touch "build/ios/Release-iphoneos/${pod}/${bundle_name}.bundle/$(basename ${bundle_name})"
              echo "Created ${pod}/${bundle_name}.bundle"
            done
          done
          
          # Hiển thị số lượng bundles đã tạo
          find build/ios/Release-iphoneos -name "*.bundle" | wc -l
      
      - name: Create Firebase privacy bundle
        script: |
          # Tạo thư mục FirebaseCoreInternal cụ thể
          mkdir -p build/ios/Release-iphoneos/FirebaseCoreInternal/FirebaseCoreInternal_Privacy.bundle
          touch build/ios/Release-iphoneos/FirebaseCoreInternal/FirebaseCoreInternal_Privacy.bundle/FirebaseCoreInternal_Privacy
          
          echo "Created FirebaseCoreInternal privacy bundle"
          
          # Kiểm tra xem file đã tạo thành công chưa
          ls -la build/ios/Release-iphoneos/FirebaseCoreInternal/FirebaseCoreInternal_Privacy.bundle/
      
      - name: Create .xcode.env.local
        script: |
          cd ios
          
          # Tạo file .xcode.env.local với các cài đặt đặc biệt
          cat > .xcode.env.local << EOF
          VALIDATE_WORKSPACE=NO
          VALIDATE_PRODUCT=NO
          SKIP_INSTALL=YES
          DISABLE_BUNDLE_VALIDATION=YES
          GCC_WARN_INHIBIT_ALL_WARNINGS=YES
          SWIFT_SUPPRESS_WARNINGS=YES
          CODE_SIGNING_ALLOWED=NO
          CODE_SIGNING_REQUIRED=NO
          EOF
          
          cd ..
      
      - name: Flutter packages get
        script: |
          flutter packages pub get
      
      - name: Build iOS app with XCBuild directly
        script: |
          # Xóa cache trước khi build
          flutter clean
          
          # Cài đặt pods với cập nhật nhưng không kiểm tra validation
          cd ios
          pod install --repo-update
          cd ..
          
          # Build iOS app với tuỳ chọn không sign và tắt validation
          flutter build ios --release --no-codesign --no-tree-shake-icons
    
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/archive/Runner.xcarchive
      - "/tmp/xcodebuild_logs/*.log"
      - flutter_drive.log
