workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA
        script: |
          # Build file .ipa mà không cần code sign
          flutter build ipa --no-codesign

    artifacts:
      # Chỉ định nơi Codemagic tìm file .ipa để hiển thị trong Artifacts
      - build/ios/ipa/*.ipa
