workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.note
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Configure code signing settings"
      
      - name: Create all required privacy bundles
        script: |
          cd $CM_BUILD_DIR
          # Danh sách các plugin cần privacy bundle
          PRIVACY_PLUGINS=(
            "permission_handler_apple:standard"
            "shared_preferences_foundation:standard"
            "in_app_purchase_storekit:standard"
            "path_provider_foundation:standard"
            "nanopb:standard"
            "leveldb-library:special:leveldb_Privacy"
            "image_picker_ios:standard"
            "google_sign_in_ios:standard"
            "flutter_local_notifications:standard"
            "connectivity_plus:standard"
            "abseil:special:xcprivacy"
            "GoogleUtilities:special:GoogleUtilities_Privacy"
            "GTMSessionFetcher:special:GTMSessionFetcher_Full_Privacy"
            "GTMSessionFetcher:special:GTMSessionFetcher_Core_Privacy"
            "BoringSSL-GRPC:special:openssl_grpc"
            "AppAuth:special:AppAuthCore_Privacy"
          )
          
          # Tạo thư mục gốc
          mkdir -p build/ios/Release-iphoneos
          
          # Tạo privacy bundles cho từng plugin
          for plugin_info in "${PRIVACY_PLUGINS[@]}"
          do
            # Tách thông tin plugin
            IFS=':' read -r plugin type bundle_name <<< "$plugin_info"
            
            if [[ "$type" == "special" ]]; then
              echo "Creating special privacy bundle: $plugin/$bundle_name.bundle"
              mkdir -p "build/ios/Release-iphoneos/${plugin}/${bundle_name}.bundle"
              touch "build/ios/Release-iphoneos/${plugin}/${bundle_name}.bundle/${bundle_name}"
            else
              echo "Creating standard privacy bundle for $plugin"
              mkdir -p "build/ios/Release-iphoneos/${plugin}/${plugin}_privacy.bundle"
              touch "build/ios/Release-iphoneos/${plugin}/${plugin}_privacy.bundle/${plugin}_privacy"
            fi
          done
          
          # Hiển thị danh sách các thư mục đã tạo
          ls -la build/ios/Release-iphoneos/
      
      - name: Flutter packages get
        script: |
          flutter packages pub get
      
      - name: Build iOS app
        script: |
          # Xóa cache trước khi build
          flutter clean
          
          # Cài đặt pods với cập nhật
          cd ios
          pod install --repo-update
          cd ..
          
          # Build iOS app với tùy chọn --no-codesign
          flutter build ios --release --no-codesign
    
    artifacts:
      - build/ios/iphoneos/Runner.app
      - "/tmp/xcodebuild_logs/*.log"
      - flutter_drive.log
