workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..

      - name: Prepare privacy bundles
        script: |
          mkdir -p ios/build/ios/Debug-iphoneos
          
          # Danh sách các plugin cần privacy bundle
          PRIVACY_PLUGINS=(
            "permission_handler_apple"
            "shared_preferences_foundation"
            "in_app_purchase_storekit"
            "path_provider_foundation"
            "nanopb"
            "leveldb-library"
            "image_picker_ios"
            "google_sign_in_ios"
            "flutter_local_notifications"
            "connectivity_plus"
          )
          
          # Tạo thư mục và file cho từng plugin
          for plugin in "${PRIVACY_PLUGINS[@]}"
          do
            # Xử lý đặc biệt cho plugin có tên khác định dạng
            if [[ "$plugin" == "nanopb" || "$plugin" == "leveldb-library" ]]; then
              mkdir -p "ios/build/ios/Debug-iphoneos/${plugin}/${plugin}_Privacy.bundle"
              touch "ios/build/ios/Debug-iphoneos/${plugin}/${plugin}_Privacy.bundle/${plugin}_Privacy"
            else
              mkdir -p "ios/build/ios/Debug-iphoneos/${plugin}/${plugin}_privacy.bundle"
              touch "ios/build/ios/Debug-iphoneos/${plugin}/${plugin}_privacy.bundle/${plugin}_privacy"
            fi
            echo "Created privacy bundle for $plugin"
          done

      - name: Build IPA
        script: |
          # Build file .ipa mà không cần code sign
          flutter build ipa --no-codesign --debug

    artifacts:
      # Chỉ định nơi Codemagic tìm file .ipa để hiển thị trong Artifacts
      - build/ios/ipa/*.ipa

  ios-workflow:
    name: iOS Build
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.note
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Configure code signing settings"
      - name: Configure iOS project
        script: |
          cd ios
          pod update
          rm -rf ./build
          mkdir -p build/ios/Debug-iphoneos/permission_handler_apple/permission_handler_apple_privacy.bundle
          touch build/ios/Debug-iphoneos/permission_handler_apple/permission_handler_apple_privacy.bundle/permission_handler_apple_privacy
          mkdir -p build/ios/Debug-iphoneos/shared_preferences_foundation/shared_preferences_foundation_privacy.bundle
          touch build/ios/Debug-iphoneos/shared_preferences_foundation/shared_preferences_foundation_privacy.bundle/shared_preferences_foundation_privacy
          cd ..
      - name: Flutter packages get
        script: |
          flutter packages pub get
      - name: Flutter build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - "/tmp/xcodebuild_logs/*.log"
      - flutter_drive.log
