// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdp-KUweRcJOBoy6jEOCfx6T8Kc8GGiEE',
    appId: '1:210983975521:web:afecb231c6bbebf1340820',
    messagingSenderId: '210983975521',
    projectId: 'note-app-f9cc7',
    authDomain: 'note-app-f9cc7.firebaseapp.com',
    storageBucket: 'note-app-f9cc7.firebasestorage.app',
    measurementId: 'G-1Q17ZJGYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90PsJGPLbeb0_zM4aC2uPp4jRdc3TkRs',
    appId: '1:210983975521:android:4655e01d9c2b2188340820',
    messagingSenderId: '210983975521',
    projectId: 'note-app-f9cc7',
    storageBucket: 'note-app-f9cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GidORb4pYDiD1GBVKiq5_Tnrfzvd_KI',
    appId: '1:210983975521:ios:3263fc14d49d383b340820',
    messagingSenderId: '210983975521',
    projectId: 'note-app-f9cc7',
    storageBucket: 'note-app-f9cc7.firebasestorage.app',
    androidClientId: '210983975521-3qvcsj4k106jr4p6vbbd5s3pcpmut3l3.apps.googleusercontent.com',
    iosClientId: '210983975521-g4frl2d3vmpdqgjfog6tucgu1k87trqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GidORb4pYDiD1GBVKiq5_Tnrfzvd_KI',
    appId: '1:210983975521:ios:3263fc14d49d383b340820',
    messagingSenderId: '210983975521',
    projectId: 'note-app-f9cc7',
    storageBucket: 'note-app-f9cc7.firebasestorage.app',
    androidClientId: '210983975521-3qvcsj4k106jr4p6vbbd5s3pcpmut3l3.apps.googleusercontent.com',
    iosClientId: '210983975521-g4frl2d3vmpdqgjfog6tucgu1k87trqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdp-KUweRcJOBoy6jEOCfx6T8Kc8GGiEE',
    appId: '1:210983975521:web:5b1859c5f7427d57340820',
    messagingSenderId: '210983975521',
    projectId: 'note-app-f9cc7',
    authDomain: 'note-app-f9cc7.firebaseapp.com',
    storageBucket: 'note-app-f9cc7.firebasestorage.app',
    measurementId: 'G-ZMF8EHW14N',
  );
}
